[package]
name = "rpi_led_matrix"
version = "0.1.0"
authors = ["Alex Eden <alexandereden91@gmail.com>"]
edition = "2018"

[[example]]
name = "minimal"
path = "examples/minimal.rs"

[dependencies]
libc = "0.2.77"

[build-dependencies]
cc = "1.0.60"
